### ISSUE TITLE
EditText is scrollable?? 

### ISSUE THREAD

**Issue by Nugetzrul3** [Nugetzrul3/Sugarchain-Android-Miner#4]
Will investigate and find solution

**Comment by cryptozeny** [comment]
![image](https://user-images.githubusercontent.com/37016180/71768958-96b38480-2f5e-11ea-8855-48f2c9c3e6c9.png)

**Comment by Nugetzrul3** [comment]
Fixed:
https://github.com/Nugetzrul3/Sugarchain-Android-Miner/commit/ca0b5bfec65fa6bede11fef7221f783349496281
